In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,NaN,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,NaN,2,125510.82,1,1,1,79084.10,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           9979 non-null   object
 6   Age              9990 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

## Data Cleaning

In [5]:
df["Gender"] = df["Gender"].fillna("Male")

In [6]:
df["Age"] = df["Age"].fillna(df.Age.mean())

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [9]:
df.drop(columns=["RowNumber","CustomerId","Surname"],inplace=True,axis=1)

In [10]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Male,38.924825,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41.000000,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42.000000,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39.000000,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,38.924825,2,125510.82,1,1,1,79084.10,0

# Label Encoding

In [12]:
le = preprocessing.LabelEncoder()
df["Gender_Label"] = le.fit_transform(df.Gender.values)

In [13]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label
0,619,France,Male,38.924825,2,0.00,1,1,1,101348.88,1,1
1,608,Spain,Female,41.000000,1,83807.86,1,0,1,112542.58,0,0
2,502,France,Female,42.000000,8,159660.80,3,1,0,113931.57,1,0
3,699,France,Female,39.000000,1,0.00,2,0,0,93826.63,0,0
4,850,Spain,Female,38.924825,2,125510.82,1,1,1,79084.10,0,0

In [15]:
df.drop(columns=["Gender"],inplace=True,axis=1)

# One Hot Encoding

In [18]:
one_hot = pd.get_dummies(df, dtype=int)
one_hot.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label,Geography_France,Geography_Germany,Geography_Spain
0,619,38.924825,2,0.00,1,1,1,101348.88,1,1,1,0,0
1,608,41.000000,1,83807.86,1,0,1,112542.58,0,0,0,0,1
2,502,42.000000,8,159660.80,3,1,0,113931.57,1,0,1,0,0
3,699,39.000000,1,0.00,2,0,0,93826.63,0,0,1,0,0
4,850,38.924825,2,125510.82,1,1,1,79084.10,0,0,0,0,1

# Dummy Encoding

In [19]:
dummy = pd.get_dummies(df, dtype=int, drop_first = True)
dummy.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Label,Geography_Germany,Geography_Spain
0,619,38.924825,2,0.00,1,1,1,101348.88,1,1,0,0
1,608,41.000000,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,42.000000,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39.000000,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,38.924825,2,125510.82,1,1,1,79084.10,0,0,0,1