In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("churn.csv")

In [4]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [8]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [9]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

Practice Questions
Description
You are given a list of string elements and asked to return a list which contains each element of the string in title case or in other words first character of the string would be in upper case and remaining all characters in lower case

Sample Input: ['VARMA', 'raj', 'Gupta', 'SaNdeeP']

Sample Output ['Varma', 'Raj', 'Gupta', 'Sandeep']

In [10]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
RowNumber,1,2,3,4,5,6,7,8,9,10,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,10000
CustomerId,15634602,15647311,15619304,15701354,15737888,15574012,15592531,15656148,15792365,15592389,...,15798964,15769959,15657105,15569266,15719294,15606229,15569892,15584532,15682355,15628319
Surname,Hargrave,Hill,Onio,Boni,Mitchell,Chu,Bartlett,Obinna,He,H?,...,Nkemakonam,Ajuluchukwu,Chukwualuka,Rahman,Wood,Obijiaku,Johnstone,Liu,Sabbatini,Walker
CreditScore,619,608,502,699,850,645,822,376,501,684,...,714,597,726,644,800,771,516,709,772,792
Geography,France,Spain,France,France,Spain,Spain,France,Germany,France,France,...,Germany,France,Spain,France,France,France,France,France,Germany,France
Gender,Female,Female,Female,Female,Female,Male,Male,Female,Male,Male,...,Male,Female,Male,Male,Female,Male,Male,Female,Male,Female
Age,42,41,42,39,43,44,50,29,44,27,...,33,53,36,28,29,39,35,36,42,28
Tenure,2,1,8,1,2,8,7,4,4,2,...,3,4,2,7,2,5,10,7,3,4
Balance,0.0,83807.86,159660.8,0.0,125510.82,113755.78,0.0,115046.74,142051.07,134603.88,...,35016.6,88381.21,0.0,155060.41,0.0,0.0,57369.61,0.0,75075.31,130142.79
NumOfProducts,1,1,3,2,1,2,2,4,2,1,...,1,1,1,1,2,2,1,1,2,1
HasCrCard,1,0,1,0,1,1,1,1,0,1,...,1,1,1,1,0,1,1,0,1,1
IsActiveMember,1,1,0,0,1,0,1,0,1,1,...,0,0,0,0,0,0,1,1,0,0
EstimatedSalary,101348.88,112542.58,113931.57,93826.63,79084.1,149756.71,10062.8,119346.88,74940.5,71725.73,...,53667.08,69384.71,195192.4,29179.52,167773.55,96270.64,101699.77,42085.58,92888.52,38190.78
Exited,1,0,1,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,1,1,0

In [16]:
df.sort_values('Age').T

,3512,1678,3517,9520,2021,9526,746,9029,4716,7722,...,9080,4931,766,9309,3531,3387,3033,2458,6759,6443
RowNumber,3513,1679,3518,9521,2022,9527,747,9030,4717,7723,...,9081,4932,767,9310,3532,3388,3034,2459,6760,6444
CustomerId,15657779,15569178,15757821,15673180,15795519,15665521,15787619,15722701,15805764,15570086,...,15620443,15772341,15810864,15621644,15653251,15798024,15578006,15813303,15660878,15764927
Surname,Boylan,Kharlamov,Burgess,Onyekaozulu,Vasiliev,Chiazagomekpele,Hsieh,Bruno,Hallahan,Lynch,...,Fiorentino,Hs?eh,Williamson,Lombardi,Hickey,Lori,Yao,Rearick,T'ien,Rogova
CreditScore,806,570,771,727,716,642,844,594,646,684,...,711,682,700,678,408,537,787,513,705,753
Geography,Spain,France,Spain,Germany,Germany,Germany,France,Germany,France,Germany,...,France,Germany,France,Germany,France,Germany,France,Spain,France,France
Gender,Male,Female,Male,Female,Female,Male,Male,Male,Male,Male,...,Female,Male,Female,Male,Female,Male,Female,Male,Male,Male
Age,18,18,18,18,18,18,18,18,18,18,...,81,81,82,83,84,84,85,88,92,92
Tenure,3,4,1,2,3,5,2,1,10,9,...,6,6,2,6,8,8,10,10,1,3
Balance,0.0,82767.42,0.0,93816.7,128743.8,111183.53,160980.03,132694.73,0.0,90544.0,...,0.0,122029.15,0.0,123356.63,87873.39,92242.34,0.0,0.0,126076.24,121513.31
NumOfProducts,2,1,2,2,1,2,1,1,2,1,...,2,1,2,1,1,1,2,2,2,1
HasCrCard,1,1,0,1,0,0,0,1,0,0,...,1,1,0,0,0,1,1,1,1,0
IsActiveMember,1,0,0,0,0,1,0,0,1,1,...,1,1,1,1,0,1,1,1,1,1
EstimatedSalary,86994.54,71811.9,41542.95,126172.11,197322.13,10063.75,145936.28,167689.56,52795.15,4777.23,...,72276.24,50783.88,182055.36,92934.41,188484.52,186235.98,116537.96,52952.24,34436.83,195563.99
Exited,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [17]:
df['Balance']

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [18]:
df.Balance

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [19]:
df["New_Balance"] = df["Balance"] + 1000
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New_Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82

In [20]:
df["Day"] = "Good Day"
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New_Balance,Day
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00,Good Day
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86,Good Day
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80,Good Day
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00,Good Day
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82,Good Day

In [22]:
df[0:1]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New_Balance,Day
0,1,15634602,Hargrave,619,France,Female,42,2,0.0,1,1,1,101348.88,1,1000.0,Good Day

In [23]:
new_df = df[df.Age > 50]
new_df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New_Balance,Day
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1,133602.88,Good Day
41,42,15738148,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1,123522.32,Good Day
42,43,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0,118419.35,Good Day
44,45,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0,156931.11,Good Day
58,59,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1,1000.00,Good Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,9937,15653037,Parks,609,France,Male,77,1,0.00,1,0,1,18708.76,0,1000.00,Good Day
9939,9940,15808971,Lajoie,693,Spain,Female,57,9,0.00,2,1,1,135502.77,0,1000.00,Good Day
9948,9949,15735078,Onwughara,724,Germany,Female,53,1,139687.66,2,1,1,12913.92,0,140687.66,Good Day
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0,91022.85,Good Day
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1,89381.21,Good Day

In [24]:
df.Age.fillna(10)

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [26]:
new_df.pop("RowNumber")

16        17
41        42
42        43
44        45
58        59
        ...
9936    9937
9939    9940
9948    9949
9979    9980
9991    9992
Name: RowNumber, Length: 1261, dtype: int64

In [27]:
new_df

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New_Balance,Day
16,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1,133602.88,Good Day
41,15738148,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1,123522.32,Good Day
42,15687946,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0,118419.35,Good Day
44,15684171,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0,156931.11,Good Day
58,15623944,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1,1000.00,Good Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,15653037,Parks,609,France,Male,77,1,0.00,1,0,1,18708.76,0,1000.00,Good Day
9939,15808971,Lajoie,693,Spain,Female,57,9,0.00,2,1,1,135502.77,0,1000.00,Good Day
9948,15735078,Onwughara,724,Germany,Female,53,1,139687.66,2,1,1,12913.92,0,140687.66,Good Day
9979,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0,91022.85,Good Day
9991,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1,89381.21,Good Day

In [30]:
new = new_df.drop("CustomerId", axis = 1)
new

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New_Balance,Day
16,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1,133602.88,Good Day
41,Clarke,465,France,Female,51,8,122522.32,1,0,0,181297.65,1,123522.32,Good Day
42,Osborne,556,France,Female,61,2,117419.35,1,1,1,94153.83,0,118419.35,Good Day
44,Bianchi,660,Spain,Female,61,5,155931.11,1,1,1,158338.39,0,156931.11,Good Day
58,T'ien,511,Spain,Female,66,4,0.00,1,1,0,1643.11,1,1000.00,Good Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,Parks,609,France,Male,77,1,0.00,1,0,1,18708.76,0,1000.00,Good Day
9939,Lajoie,693,Spain,Female,57,9,0.00,2,1,1,135502.77,0,1000.00,Good Day
9948,Onwughara,724,Germany,Female,53,1,139687.66,2,1,1,12913.92,0,140687.66,Good Day
9979,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0,91022.85,Good Day
9991,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1,89381.21,Good Day

In [31]:
import numpy as np
df['Square_Balance'] = df.Balance.apply(np.sqrt)

In [32]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New_Balance,Day,Square_Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00,Good Day,0.000000
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86,Good Day,289.495872
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80,Good Day,399.575775
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00,Good Day,0.000000
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82,Good Day,354.275063

In [33]:
df.Age.dropna()

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

## Concat & Merging

In [37]:
df_dict = pd.DataFrame({"A":["A0","A1","A2","A3"],
                       "B":["B0","B1","B2","B3"],
                       "C":["C0","C1","C2","C3"],
                       "D":["D0","D1","D2","D3"]}, 
                        index=[0,1,2,3]
                      )

In [38]:
df_dict2 = pd.DataFrame({"A":["A4","A5","A6","A7"],
                         "B":["B4","B5","B6","B7"],
                         "C":["C4","C5","C6","C7"],
                         "D":["D4","D5","D6","D7"]},
                        index=[4,5,6,7]
                       )

In [39]:
result = pd.concat([df_dict,df_dict2])

In [40]:
df_dict

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [41]:
df_dict2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [42]:
result

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [49]:
df_dict2 = pd.DataFrame({"E":["A4","A5","A6","A7"],
                         "F":["B4","B5","B6","B7"],
                         "C":["C0","C1","C2","C3"],
                         "D":["D0","D1","D2","D3"]},
                       )

In [52]:
df_merge = pd.merge(df_dict, df_dict2)

In [68]:
df_merge

    A   B   C   D   E   F
0  A0  B0  C0  D0  A4  B4
1  A1  B1  C1  D1  A5  B5
2  A2  B2  C2  D2  A6  B6
3  A3  B3  C3  D3  A7  B7

In [73]:
pd.merge(df_dict,df_dict2,on=["C","D"],how="right")

    A   B   C   D   E   F
0  A0  B0  C0  D0  A4  B4
1  A1  B1  C1  D1  A5  B5
2  A2  B2  C2  D2  A6  B6
3  A3  B3  C3  D3  A7  B7

### loc vs iloc

In [57]:
s = pd.Series(list("SameenZaki"),index=[10,11,12,13,14,15,16,17,18,19])
s

10    S
11    a
12    m
13    e
14    e
15    n
16    Z
17    a
18    k
19    i
dtype: object

In [59]:
s.loc[10]

'S'

In [60]:
s.iloc[0]

'S'

In [63]:
s.loc[10:13]

10    S
11    a
12    m
13    e
dtype: object

In [65]:
s.iloc[-4:]

16    Z
17    a
18    k
19    i
dtype: object

In [66]:
s.sort_index()

10    S
11    a
12    m
13    e
14    e
15    n
16    Z
17    a
18    k
19    i
dtype: object

In [67]:
s.sort_values()

10    S
16    Z
11    a
17    a
13    e
14    e
19    i
18    k
12    m
15    n
dtype: object